### ISSUE TITLE
Stack overflow on regexps with large occurrence numbers

### ISSUE THREAD

**Issue by a3nm** [PoDMR/enum-spanner-rs#1]
Hi,

There seems to be a stack overflow when compiling regexps with large occurrence numbers:

```
$ echo a | cargo run --release -- -b ".{0,10000}" 
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/enum-spanner-rs -b '.{0,10000}'`

thread 'main' has overflowed its stack
fatal runtime error: stack overflow
zsh: done       echo a | 
zsh: abort      cargo run --release -- -b ".{0,10000}"
```

**Comment by niewerth** [comment]
Actually this was a problem with large concatenations. There also was a stack overflow when just searching for a long string. This also affected repetitions, as repetition is converted to concatenation in the Glushkov construction.

This was fixed in master by changing the concatenation operator to k-ary (instead of binary).

**Comment by a3nm** [comment]
Thanks! Now it works, slowly (which I guess is expected given our dependency on automaton size), but it doesn't crash and gives the correct result on my machine too.
